# This workflow will scan a .NET project
# For more information see: https://devblogs.microsoft.com/nuget/how-to-scan-nuget-packages-for-security-vulnerabilities/#dotnet-cli

name: CVE Scanning for Docker

on:
  push:
    paths:
      - 'docker/Dockerfile'
      - '.github/workflows/cve-scanning-docker.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build -f Dockerfile -t user/app:latest
        working-directory: docker
      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: user/app:latest