name: Poetry CI

on:
  push:
    paths:
      - 'python/'

jobs:
  test:
    name: Build and test App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install poetry
        run: pip install poetry
        working-directory: python
      - name: Build app
        run: poetry build
        working-directory: python
      - name: Test app
        run: |
          poetry install
          poetry run coverage run -m pytest
          poetry run coverage report
          poetry run coverage xml
        working-directory: python
  publish:
    name: Publish App on PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install poetry
        run: pip install poetry
        working-directory: python
      - name: Scan CVEs
        run: poetry export --without-hashes -f requirements.txt | safety check --full-report --stdin
        working-directory: python
      - name: Publish app
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build --username "__token__" --password "$PYPI_TOKEN"
        working-directory: python